# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
<<<<<<< Updated upstream
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
=======

jobs:
  test:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run dev

  lint:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      

  prepublish:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Prepare for publishing
          command: npm run prepublish

  dev:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start development server
          command: npm run dev

>>>>>>> Stashed changes
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag          
          # Relevant tags can be found on the CircleCI Developer Hub
          app-dir: ~../../../project/soen390_web
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
