version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run dev

  lint:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      

  prepublish:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Prepare for publishing
          command: npm run prepublish

  dev:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start development server
          command: npm run dev

workflows:
  sample:
    jobs:
      - node/test:
          app-dir: ~../../../project/soen390_backend
          version: '16.10'
          pkg-manager: npm
      - test
      - build
      - lint
      - prepublish
      - dev
