name: CI test backend and frontend

on:
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: NPM Install Dependencies
              run: |
                  echo Is npm installed?
                  npm -v
                  echo Is git installed?
                  git --version
                  echo Is Node installed?
                  node -v
                  echo Install Dependencies
                  cd soen390_web
                  npm install --force
                  cd ..
                  cd soen390_backend
                  npm i
                  cd ..

            - name: Install dotenv
              run: |
                  cd soen390_backend
                  npm install dotenv --save-dev

            - name: Create env file
              env:
                  ENV_FILE: ${{ secrets.ENV_FILE }}
              run: |
                  echo "${ENV_FILE}" > .env.template
                  envsubst < .env.template > .env

            - name: Run Tests
              if: always()
              run: |
                  cd soen390_backend
                  npm run test
